### ISSUE TITLE
cm-13.0-20160616-NIGHTLY Samsung S3 i9300 SystemUI force close

### ISSUE THREAD

**Issue by xpduyson** [paphonbth/CustomBatteryMeter#1]
https://gist.githubusercontent.com/xpduyson/128a1cd847b5d1f7b37da8856dd34900/raw/4a3a7063438f452ce10609530cbc0d814c9eebdf/gistfile1.txt

**Comment by suphon-t** [comment]
Thanks. Will upload a fix soon.

**Comment by xpduyson** [comment]
fixed
