### ISSUE TITLE
please fix battery theming on my sony ericsson wt19a

### ISSUE THREAD

**Issue by nithin-chandra** [paphonbth/CustomBatteryMeter#3]
im unable to experience battery theming in my device friend..as im using the latest xposed v86...my os platform is LP...with resurrection remix...UI is also not restarted when i make a try...it is enabling some error logs like this...
![screenshot_2016-07-12-11-25-50](https://cloud.githubusercontent.com/assets/20321139/16757690/2dd8484c-482b-11e6-997d-6483e735720c.png)
![screenshot_2016-07-12-11-24-59](https://cloud.githubusercontent.com/assets/20321139/16757692/33bf0610-482b-11e6-9369-9da4961e7b3f.png)

**Comment by suphon-t** [comment]
Please upload the log file.
Some useful information in the screenshot is off the screen.

**Comment by nithin-chandra** [comment]
[xposed_error_20160712_181053.log.zip](https://github.com/paphonbth/CustomBatteryMeter/files/359328/xposed_error_20160712_181053.log.zip)
trace the log friend

**Comment by nithin-chandra** [comment]
i attached log file in github friend....once have a look at that and try to
fix for my device

**Comment by suphon-t** [comment]
Should be fixed now.

**Comment by nithin-chandra** [comment]
i appreciate with all of your hardwork friend....you are too genius
